name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Add static export config to next.config.js
        run: |
          if ! grep -q "output: 'export'" next.config.js; then
            cp next.config.js next.config.js.backup
            sed "s/const nextConfig = {/const nextConfig = {\n  output: 'export',/" next.config.js > tmp.js
            mv tmp.js next.config.js
          fi

      - name: Build site
        run: yarn build

      - name: Export static site
        run: yarn next export

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
